backend:
  name: github
  repo: Energetics-Incorporated/gctc # Path to your Github repository
  branch: master
  
  media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads  
  public_folder: "img/uploads" # The src attribute for uploaded media will begin with /images/uploads
  
collections:
- name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}