backend:
  name: github
  repo: Energetics-Incorporated/gctc # Path to your Github repository
  branch: master # Branch to update
  publish_mode: editorial_workflow
  media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
  public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "faq" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "FAQ" # Used in the UI, ie.: "New Post"
    folder: "_faqs"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Question", name: "title", widget: "string", tagname: "h1"}
      - {label: "Answer", name: "body", widget: "markdown"}
    card: {type: "alltype", text: "title"}