backend:
  name: github
  repo: Energetics-Incorporated/gctc # Path to your Github repository


  media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
  
  public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
  
collections:
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    folder: "content"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Question", name: "title", widget: "string", tagname: "h1"}
      - {label: "Answer", name: "body", widget: "markdown"}
    card: {type: "alltype", text: "title"}